package pe.com.gesateped.carga.registro.validation;

public enum RegistroCargaErrorCode {

	ERROR_VALIDACION_ITEM_INCOMPLETO,
	ERROR_VALIDACION_PRODUCTO_NO_EXISTE,
	ERROR_VALIDACION_PRODUCTO_NOMBRE_NO_VALIDO,
	VALIDACION_PRODUCTO_CODIGO_VACIO,
	VALIDACION_PRODUCTO_NOMBRE_VACIO,
	VALIDACION_CANTIDAD_OBLIGATORIA,
	VALIDACION_CANTIDAD_INADECUADA,
	BASE_DE_DATOS,
	BD_NO_SE_ENCUENTRA_EN_KARDEX,
	BD_STOCK_EN_BODEGA_INSUFICIENTE,
	BD_NO_SE_ENCUENTRA_EN_KARDEX_PARA_BODEGA,
	BD_YA_SE_REGISTRO,
	ERROR_GENERAL
}
